apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    kind: localpv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/Dev6/code/"
